# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ramcharancholleti@gmail.com
author_name: Ramcharan1706
contract_name: algo_token
deployment_language: python
preset_name: starter
project_name: algo_token-contracts

